version: '3.8'
services:
  database-mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_PASSWORD=ngoc21062001
    ports:
      - '3307:3306'
    expose:
      - 3306

  backend:
    build:
      context: ../../Hotel-Management-API
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=database-mysql
      # - DB_HOST=host.docker.internal
    ports:
      - 8080:8080

# docker compose -p hotel-management-api-sql up -d
